apiVersion: v1
kind: Service
metadata:
  name: golang-http-test
spec:
  selector:
    app: golang-http-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  - name: test-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP